### ISSUE TITLE
collect_logs target bug

### ISSUE THREAD

**Issue by chrispbradley** [OpenCMISS/manage#62]
I've been having a problem with the collect_logs target i.e.,

CMake Error at CMakeScripts/OCComponentSetupMacros.cmake:363 (add_custom_command):
  The target name "collect_logs" is unknown in this context.
Call Stack (most recent call first):
  CMakeScripts/OCComponentSetupMacros.cmake:274 (doSupportStuff)
  Tests/OCExamplesTests.cmake:29 (createExternalProjects)
  Tests/CMakeLists.txt:2 (include)

This happens when it is trying to process the examples tests (i.e., classicalfield_laplace_simple). From a quick google I think this is because custom commands can only be attached to targets in the same directory. The add_custom_target for collect_logs is defined in the manage directory but the OCExamplesTests executes from the manage/Tests directory. The current fix is to comment out the OCExamplesTests include but this will need to be addressed in the future.

**Comment by nickerso** [comment]
an alternate workaround is to set `OC_CREATE_LOGS` to `NO`.

**Comment by chrispbradley** [comment]
Strangely, that did not work. Once I encountered the bug I couldn't get rid of it. Even completely deleting all build directories and trying to configure from scratch still gave me the error. Another issue perhaps.

**Comment by rondiplomatico** [comment]
This was a problem introduced by moving the test stuff into an actual subdirectory - the support custom build target "collect_logs" was defined in the top level, and one of the macros invoked when using "createExternalProjects" (here in Tests/OCExamplesTests.cmake) tried to add a custom command depending on this target, which was defined in another folder. this CMake behaviour can be discussed of course - but for now i've simply created custom targets instead of commands and this does the job just as well. as this effectively affects all the default builds for users (developers have OC_CREATE_LOGS to NO automatically), i'll cherry-pick this commit also into the v1.2 release branch.
