### ISSUE TITLE
Architecture Path detail

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS/manage#9]
Currently there's the full compiler version used in the arch path, possibly leading to gnu-4.5.7 and gnu-4.5.8 folders etc. as this path's main intention is to ensure compatible libraries for a given configuration, two questions arise:
- do we need the PATCH part (in any case / the gnu compiler case?)
- currently this version is taken from the C compiler. what if the fortran compiler has a different version or is maybe even from another toolchain? regarding the f90 .mod-files this could cause trouble as well. so do we need to add the fortran-compiler version somehow suitably (e.g. gnu-cc-4.6-gfortran-4.5)?

**Comment by chrispbradley** [comment]
The reason why the version number is in the arch path is because of either binary or module file incompatibility. This normally occurs between major or minor versions of compilers. Releases of patch versions are normally compatible. I this don't think we need the patch version in the arch path.

With regard to tool chain then shouldn't we set the tool chain and then find compilers? If not then if we want to be safe then shouldn't we concatenation C and Fortran compiler paths in the arch path?
